version: "3.2"

volumes:
  djangodocker.db.volume:

services:
  app:
    container_name: djangodocker.app
    build:
      context: .
      args:
        requirements: requirements/development.txt
        DJANGO_SETTINGS_MODULE: djangodocker.settings.development
    environment:
    - DJANGO_SETTINGS_MODULE=djangodocker.settings.development
    command: uwsgi --http :8001 --module djangodocker.wsgi
    volumes:
    - ./:/app
    networks:
    - main  # Add the container to the network "main"
    depends_on:
    - db

  db:
    image: mysql:5.7.22
    container_name: djangodocker.db
    environment:
      MYSQL_DATABASE: djangodocker_db
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    networks:
    - main  # Add the container to the network "main"
    volumes:
      - djangodocker.db.volume:/var/lib/mysql
    ports:
    - "3306:3306"

  nginx:
    container_name: djangodocker.nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
#      - ./nginx/log:/var/log/nginx
      - ./static:/usr/share/nginx/djangodocker/static
    ports:
    - "80:80"
    networks:
    - main  # Add the container to the network "main"
    depends_on:
    - app
networks:
  main:
